name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get install python3
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        e
    - name: Test with pytest
      run: |
        pytest
